import { ReportData } from '../App';

/**
 * Generates an executive, publication-grade, self-contained HTML dossier
 * formatted with responsive typography, financial indicators, and styling.
 */
export function generateExecutiveHTMLReport(
  data: ReportData,
  ticker: string,
  metrics?: {
    durationSecs?: number;
    toolRuns?: number;
    tokenCount?: number;
    documentCount?: number;
  }
): string {
  const verdict = data.verdict || {
    summary: 'Autonomous financial intelligence report generated by AgentSamFast.',
    key_takeaways: [],
    conviction_score: 75,
  };

  const takeaways = Array.isArray(verdict.key_takeaways)
    ? verdict.key_takeaways
    : [String(verdict.key_takeaways || '')];

  const score = verdict.conviction_score || 70;
  const scoreColor = score >= 80 ? '#0b5a4b' : score >= 60 ? '#2563eb' : score >= 40 ? '#d97706' : '#dc2626';

  const stockPoints = data.financial_charts?.stock_price_4m || [];
  const perfPoints = data.financial_charts?.financial_performance_4q || [];
  const deepInsights = data.deep_insights || [];
  const findings = data.findings || [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AgentSamFast Dossier - ${ticker.toUpperCase()}</title>
  <style>
    :root {
      --bg: #F9F8F6;
      --card-bg: #FFFFFF;
      --text: #1C1917;
      --muted: #78716C;
      --border: #E7E5E4;
      --accent: #0b5a4b;
      --accent-light: #ecfdf5;
      --font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: var(--bg);
      color: var(--text);
      font-family: var(--font);
      line-height: 1.6;
      padding: 24px 16px;
      -webkit-font-smoothing: antialiased;
    }
    .container {
      max-width: 960px;
      margin: 0 auto;
    }
    header {
      display: flex;
      flex-direction: column;
      gap: 8px;
      padding-bottom: 20px;
      border-bottom: 2px solid var(--border);
      margin-bottom: 24px;
    }
    @media (min-width: 640px) {
      header {
        flex-direction: row;
        justify-content: space-between;
        align-items: flex-end;
      }
    }
    .badge {
      display: inline-block;
      padding: 4px 10px;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      border-radius: 6px;
      background: var(--accent-light);
      color: var(--accent);
      border: 1px solid rgba(11, 90, 75, 0.2);
    }
    h1 {
      font-size: 28px;
      font-weight: 800;
      letter-spacing: -0.02em;
      color: var(--text);
      margin-top: 6px;
    }
    .meta {
      font-family: var(--font-mono);
      font-size: 12px;
      color: var(--muted);
    }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 20px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.02);
    }
    .card-title {
      font-size: 14px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      color: var(--muted);
      margin-bottom: 12px;
      border-bottom: 1px solid var(--border);
      padding-bottom: 8px;
    }
    .summary-text {
      font-size: 17px;
      font-weight: 500;
      color: #292524;
      line-height: 1.6;
      background: #FAFAF9;
      padding: 16px;
      border-radius: 8px;
      border-left: 4px solid var(--accent);
      margin-bottom: 20px;
    }
    .summary-grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 20px;
    }
    @media (min-width: 768px) {
      .summary-grid {
        grid-template-columns: 7fr 3fr;
      }
    }
    .takeaway-item {
      display: flex;
      gap: 12px;
      margin-bottom: 12px;
      font-size: 15px;
      color: #44403C;
    }
    .check-icon {
      color: var(--accent);
      font-weight: bold;
      flex-shrink: 0;
    }
    .conviction-box {
      text-align: center;
      padding: 20px 12px;
      background: #FAFAF9;
      border-radius: 8px;
      border: 1px solid var(--border);
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    .score-value {
      font-size: 56px;
      font-weight: 800;
      color: ${scoreColor};
      line-height: 1;
      margin: 8px 0 4px 0;
    }
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 4px;
      width: 100%;
      margin-top: 16px;
      padding-top: 12px;
      border-top: 1px solid var(--border);
    }
    .metric-col {
      text-align: center;
    }
    .metric-label {
      font-size: 9px;
      text-transform: uppercase;
      font-weight: 700;
      color: var(--muted);
    }
    .metric-val {
      font-family: var(--font-mono);
      font-size: 13px;
      font-weight: 600;
      color: var(--text);
    }
    .charts-grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 20px;
    }
    @media (min-width: 768px) {
      .charts-grid {
        grid-template-columns: 1fr 1fr;
      }
    }
    .data-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
      font-size: 14px;
    }
    .data-table th, .data-table td {
      padding: 10px 12px;
      text-align: left;
      border-bottom: 1px solid var(--border);
    }
    .data-table th {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--muted);
      background: #FAFAF9;
    }
    .data-table td {
      font-family: var(--font-mono);
    }
    .insights-grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 16px;
    }
    @media (min-width: 768px) {
      .insights-grid {
        grid-template-columns: repeat(3, 1fr);
      }
    }
    .insight-card {
      background: #FAFAF9;
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 16px;
      display: flex;
      flex-direction: column;
    }
    .insight-cat {
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      color: var(--muted);
    }
    .insight-title {
      font-size: 15px;
      font-weight: 700;
      margin: 4px 0 8px 0;
      color: var(--text);
    }
    .insight-desc {
      font-size: 13px;
      color: #57534E;
      flex: 1;
    }
    .impact-pill {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-family: var(--font-mono);
      font-weight: 700;
      margin-top: 12px;
      align-self: flex-start;
      background: #E7E5E4;
      color: var(--text);
    }
    .finding-item {
      padding: 16px;
      background: #FAFAF9;
      border-radius: 8px;
      border: 1px solid var(--border);
      margin-bottom: 12px;
    }
    .finding-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }
    .finding-title {
      font-size: 15px;
      font-weight: 700;
      color: var(--text);
    }
    .finding-bullet {
      margin-left: 18px;
      font-size: 14px;
      color: #44403C;
      margin-bottom: 6px;
    }
    .print-btn {
      background: var(--text);
      color: #fff;
      border: none;
      padding: 8px 16px;
      border-radius: 6px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
      display: inline-flex;
      align-items: center;
      gap: 6px;
    }
    @media print {
      body { background: #fff; padding: 0; }
      .card { box-shadow: none; border: 1px solid #ccc; break-inside: avoid; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div>
        <span class="badge">AgentSamFast Autonomous Intelligence</span>
        <h1>${ticker.toUpperCase()} Synthesis Report</h1>
        <div class="meta">Generated on ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} • RAG Grounded via Cloudflare D1</div>
      </div>
      <div class="no-print" style="margin-top: 10px;">
        <button class="print-btn" onclick="window.print()">
          <span>Print / Save PDF</span>
        </button>
      </div>
    </header>

    <!-- Executive Summary Card -->
    <div class="card">
      <div class="card-title">Executive Summary</div>
      <div class="summary-text">"${verdict.summary}"</div>

      <div class="summary-grid">
        <div>
          <div style="font-size: 12px; font-weight: 700; text-transform: uppercase; color: var(--muted); margin-bottom: 12px;">Key Takeaways</div>
          ${takeaways.map(t => `
            <div class="takeaway-item">
              <span class="check-icon">✓</span>
              <span>${t}</span>
            </div>
          `).join('')}
        </div>

        <div class="conviction-box">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: var(--muted);">Conviction Score</div>
          <div class="score-value">${score}</div>
          <div style="font-size: 11px; color: var(--muted); text-transform: uppercase;">out of 100</div>

          <div class="metrics-grid">
            <div class="metric-col">
              <div class="metric-label">Docs</div>
              <div class="metric-val">${metrics?.documentCount ?? findings.length}</div>
            </div>
            <div class="metric-col">
              <div class="metric-label">Time</div>
              <div class="metric-val">${metrics?.durationSecs ?? 0}s</div>
            </div>
            <div class="metric-col">
              <div class="metric-label">Runs</div>
              <div class="metric-val">${metrics?.toolRuns ?? 0}</div>
            </div>
            <div class="metric-col">
              <div class="metric-label">Tokens</div>
              <div class="metric-val">${metrics?.tokenCount ? Math.round(metrics.tokenCount / 1000) + 'k' : '-'}</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Quantitative Tables Card -->
    ${(stockPoints.length > 0 || perfPoints.length > 0) ? `
    <div class="card">
      <div class="card-title">Quantitative Market & Financial Indicators</div>
      <div class="charts-grid">
        ${stockPoints.length > 0 ? `
          <div>
            <div style="font-size: 13px; font-weight: 700; margin-bottom: 6px;">Historical Closing Prices (4M)</div>
            <table class="data-table">
              <thead><tr><th>Date</th><th style="text-align: right;">Price</th></tr></thead>
              <tbody>
                ${stockPoints.map(p => `<tr><td>${p.date}</td><td style="text-align: right; font-weight: 700;">$${p.price}</td></tr>`).join('')}
              </tbody>
            </table>
          </div>
        ` : ''}

        ${perfPoints.length > 0 ? `
          <div>
            <div style="font-size: 13px; font-weight: 700; margin-bottom: 6px;">Quarterly Financial Performance</div>
            <table class="data-table">
              <thead><tr><th>Quarter</th><th style="text-align: right;">Revenue</th><th style="text-align: right;">Net Income</th></tr></thead>
              <tbody>
                ${perfPoints.map(p => `<tr><td>${p.quarter}</td><td style="text-align: right; color: #2563eb;">${p.revenue !== undefined ? '$' + p.revenue + 'B' : '-'}</td><td style="text-align: right; color: #1e3a8a; font-weight: 700;">${p.net_income !== undefined ? '$' + p.net_income + 'B' : '-'}</td></tr>`).join('')}
              </tbody>
            </table>
          </div>
        ` : ''}
      </div>
    </div>
    ` : ''}

    <!-- Deep Insights -->
    ${deepInsights.length > 0 ? `
    <div class="card">
      <div class="card-title">Deep Forensic Insights</div>
      <div class="insights-grid">
        ${deepInsights.map(d => `
          <div class="insight-card">
            <span class="insight-cat">${d.category}</span>
            <div class="insight-title">${d.title}</div>
            <div class="insight-desc">${d.description}</div>
            <span class="impact-pill">Impact: ${d.impact_score}/10</span>
          </div>
        `).join('')}
      </div>
    </div>
    ` : ''}

    <!-- SEC Document Findings -->
    ${findings.length > 0 ? `
    <div class="card">
      <div class="card-title">Verified SEC Document Findings</div>
      <div>
        ${findings.map(f => `
          <div class="finding-item">
            <div class="finding-header">
              <span class="finding-title">${f.documentType || f.document_type || 'Filing Disclosure'}</span>
              <span class="meta">${f.date || ''}</span>
            </div>
            <ul>
              ${(Array.isArray(f.keyInsights || f.key_insights) ? (f.keyInsights || f.key_insights) : [String(f.keyInsights || f.key_insights || '')]).map((ins: string) => `
                <li class="finding-bullet">${ins}</li>
              `).join('')}
            </ul>
          </div>
        `).join('')}
      </div>
    </div>
    ` : ''}

    <footer style="text-align: center; margin-top: 30px; font-size: 11px; color: var(--muted);">
      <div>AgentSamFast • Autonomous Multimodal Research Platform</div>
      <div>Indexed with Cloudflare D1 & Gemini 2.0 Vector Embeddings</div>
    </footer>
  </div>
</body>
</html>`;
}
