import { getAgentByName } from 'agents';

function trim(value) {
  return value == null ? '' : String(value).trim();
}

function isOwnedConversationSuffix(value) {
  const suffix = trim(value);
  if (!suffix) return false;
  // crypto.randomUUID() path used by the browser app.
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(suffix)) {
    return true;
  }
  // Date.now().toString(36) + random base36 fallback used by the browser app.
  return /^[a-z0-9]{6,}-[a-z0-9]{5,12}$/i.test(suffix);
}

/**
 * Agent names are user-scoped. Conversation agents may append only the suffix
 * formats generated by AgentShell; arbitrary user-* prefix matches are rejected.
 */
export function agentNamePrefixForUser(userId) {
  const safe = trim(userId)
    .replace(/[^a-zA-Z0-9_-]/g, '-')
    .slice(0, 72);
  if (!safe) throw new Error('browser_user_scope_required');
  return `user-${safe}`;
}

export function resolveOwnedAgentName(userId, requestedAgentName) {
  const prefix = agentNamePrefixForUser(userId);
  const requested = trim(requestedAgentName);
  if (!requested) return prefix;
  if (requested === prefix) return requested;
  if (requested.startsWith(`${prefix}-`)) {
    const suffix = requested.slice(prefix.length + 1);
    if (isOwnedConversationSuffix(suffix)) return requested;
  }
  throw new Error('browser_agent_scope_forbidden');
}

async function resolveBrowserAgent(env, userId, requestedAgentName) {
  const agentName = resolveOwnedAgentName(userId, requestedAgentName);
  const agent = await getAgentByName(env.AgentSam, agentName);
  return { agent, agentName };
}

export async function getBrowserLiveView(env, { userId, agentName }) {
  const resolved = await resolveBrowserAgent(env, userId, agentName);
  const liveView = await resolved.agent.getBrowserLiveView();
  return { ...liveView, agentName: resolved.agentName };
}

export async function closeBrowserLiveView(env, { userId, agentName }) {
  const resolved = await resolveBrowserAgent(env, userId, agentName);
  const result = await resolved.agent.closeBrowserLiveView();
  return { ...result, agentName: resolved.agentName };
}
