import React, { useState, useEffect } from 'react';
import { RepositoryIntelligenceReport } from '../../sdk/types';
import { RepositoryIntelligence } from '../../sdk/repository';

interface RepoIntelligenceViewProps {
  repoName: string;
  onStartMissionForSignal?: (signalTitle: string, description: string) => void;
}

export const RepoIntelligenceView: React.FC<RepoIntelligenceViewProps> = ({
  repoName,
  onStartMissionForSignal,
}) => {
  const [report, setReport] = useState<RepositoryIntelligenceReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'overview' | 'duplicates' | 'godfiles' | 'churn'>('overview');

  const inspector = new RepositoryIntelligence();

  useEffect(() => {
    let mounted = true;
    setLoading(true);
    inspector.inspect(repoName).then(data => {
      if (mounted) {
        setReport(data);
        setLoading(false);
      }
    });
    return () => { mounted = false; };
  }, [repoName]);

  if (loading || !report) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-12 text-zinc-400">
        <span className="material-symbols-outlined text-3xl animate-spin text-sky-400 mb-3">
          progress_activity
        </span>
        <p className="text-sm font-medium">Scanning AST & Git churn topology for {repoName}...</p>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col overflow-y-auto p-6 space-y-6 text-zinc-200">
      {/* Top Banner & Quick Metrics */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 p-5 bg-zinc-900/80 border border-zinc-800 rounded-xl backdrop-blur">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="material-symbols-outlined text-sky-400 text-xl">insights</span>
            <h2 className="text-lg font-bold text-white tracking-tight">{report.repoName}</h2>
            <span className="text-xs px-2 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-zinc-300">
              {report.branch} @ {report.commitHash}
            </span>
          </div>
          <p className="text-xs text-zinc-400">
            Automated intelligence report generated by <code className="text-sky-300 font-mono">@inneranimalmedia/agentsam-sdk/repository</code>
          </p>
        </div>

        {/* Health Score Pill */}
        <div className="flex items-center gap-6">
          <div className="text-right">
            <div className="text-2xl font-bold text-emerald-400 font-mono">{report.summary.healthScore}/100</div>
            <div className="text-[11px] text-zinc-400">Architecture Health Score</div>
          </div>
          <div className="h-10 w-px bg-zinc-800" />
          <div className="text-right">
            <div className="text-2xl font-bold text-sky-400 font-mono">{report.summary.totalLoc.toLocaleString()}</div>
            <div className="text-[11px] text-zinc-400">Total Lines of Code</div>
          </div>
        </div>
      </div>

      {/* Sub-Navigation Tabs */}
      <div className="flex border-b border-zinc-800 gap-6">
        <button
          type="button"
          onClick={() => setActiveTab('overview')}
          className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
            activeTab === 'overview'
              ? 'border-sky-400 text-sky-400'
              : 'border-transparent text-zinc-400 hover:text-zinc-200'
          }`}
        >
          <span className="material-symbols-outlined text-sm">dashboard</span>
          <span>Overview & Topology</span>
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('duplicates')}
          className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
            activeTab === 'duplicates'
              ? 'border-sky-400 text-sky-400'
              : 'border-transparent text-zinc-400 hover:text-zinc-200'
          }`}
        >
          <span className="material-symbols-outlined text-sm text-amber-400">compare_arrows</span>
          <span>Duplicate Authorities ({report.duplicateAuthoritySignals.length})</span>
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('godfiles')}
          className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
            activeTab === 'godfiles'
              ? 'border-sky-400 text-sky-400'
              : 'border-transparent text-zinc-400 hover:text-zinc-200'
          }`}
        >
          <span className="material-symbols-outlined text-sm text-rose-400">warning</span>
          <span>God File Candidates ({report.godFileCandidates.length})</span>
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('churn')}
          className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
            activeTab === 'churn'
              ? 'border-sky-400 text-sky-400'
              : 'border-transparent text-zinc-400 hover:text-zinc-200'
          }`}
        >
          <span className="material-symbols-outlined text-sm text-purple-400">trending_up</span>
          <span>Git Churn Hotspots</span>
        </button>
      </div>

      {/* TAB 1: Overview */}
      {activeTab === 'overview' && (
        <div className="space-y-6">
          {/* Summary Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-4 bg-zinc-900/60 border border-zinc-800 rounded-xl">
              <span className="text-xs text-zinc-500 font-medium">Total Files</span>
              <div className="text-xl font-bold text-zinc-100 mt-1">{report.summary.totalFiles}</div>
            </div>
            <div className="p-4 bg-zinc-900/60 border border-zinc-800 rounded-xl">
              <span className="text-xs text-zinc-500 font-medium">Test Coverage</span>
              <div className="text-xl font-bold text-emerald-400 mt-1">
                {Math.round(report.summary.testCoverageRatio * 100)}%
              </div>
            </div>
            <div className="p-4 bg-zinc-900/60 border border-zinc-800 rounded-xl">
              <span className="text-xs text-zinc-500 font-medium">Languages</span>
              <div className="text-xl font-bold text-sky-400 mt-1">{report.summary.totalLanguages}</div>
            </div>
            <div className="p-4 bg-zinc-900/60 border border-zinc-800 rounded-xl">
              <span className="text-xs text-zinc-500 font-medium">Direct Dependencies</span>
              <div className="text-xl font-bold text-purple-400 mt-1">{report.dependencyPressure.directDependencies}</div>
            </div>
          </div>

          {/* Language Breakdown */}
          <div className="p-5 bg-zinc-900/60 border border-zinc-800 rounded-xl">
            <h3 className="text-xs font-bold text-zinc-400 uppercase tracking-wider mb-4">Language Distribution</h3>
            <div className="space-y-3">
              {Object.entries(report.languageDistribution).map(([lang, stats]: [string, any]) => (
                <div key={lang} className="space-y-1">
                  <div className="flex justify-between text-xs font-mono">
                    <span className="text-zinc-200">{lang}</span>
                    <span className="text-zinc-400">{stats.percentage}% ({stats.loc?.toLocaleString()} LOC)</span>
                  </div>
                  <div className="h-1.5 w-full bg-zinc-800 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-sky-500 rounded-full"
                      style={{ width: `${stats.percentage}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Monorepo Topology */}
          <div className="p-5 bg-zinc-900/60 border border-zinc-800 rounded-xl">
            <h3 className="text-xs font-bold text-zinc-400 uppercase tracking-wider mb-4">Workspace Packages & Subtrees</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {report.workspaceTopology.packages.map(pkg => (
                <div key={pkg.name} className="p-3 bg-zinc-950/80 border border-zinc-800 rounded-lg flex items-center justify-between">
                  <div>
                    <span className="text-xs font-mono font-bold text-sky-300">{pkg.name}</span>
                    <div className="text-[11px] text-zinc-500 font-mono mt-0.5">{pkg.path}</div>
                  </div>
                  <span className="text-xs font-mono text-zinc-400">{pkg.loc.toLocaleString()} LOC</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: Duplicate Authorities */}
      {activeTab === 'duplicates' && (
        <div className="space-y-4">
          <div className="p-4 bg-amber-500/10 border border-amber-500/30 rounded-xl text-xs text-amber-300 flex items-start gap-3">
            <span className="material-symbols-outlined text-amber-400 text-lg">info</span>
            <div>
              <strong className="block font-semibold mb-0.5">Architectural Refactoring Target</strong>
              Agent Sam identified duplicated authorities between legacy modules and new SDK implementations. Consolidating these eliminates auth discrepancies and reduces maintenance debt.
            </div>
          </div>

          {report.duplicateAuthoritySignals.map((signal, idx) => (
            <div key={idx} className="p-5 bg-zinc-900/80 border border-zinc-800 rounded-xl space-y-3">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h4 className="text-sm font-bold text-white flex items-center gap-2">
                    <span className="material-symbols-outlined text-amber-400 text-base">rule</span>
                    <span>{signal.domain}</span>
                  </h4>
                  <p className="text-xs text-zinc-400 mt-1">{signal.description}</p>
                </div>
                {onStartMissionForSignal && (
                  <button
                    type="button"
                    onClick={() => onStartMissionForSignal(
                      `Eliminate duplicate authority in ${signal.domain}`,
                      signal.recommendation
                    )}
                    className="px-3 py-1.5 bg-sky-600 hover:bg-sky-500 text-white rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 shrink-0"
                  >
                    <span className="material-symbols-outlined text-sm">play_arrow</span>
                    <span>Begin Refactor Mission</span>
                  </button>
                )}
              </div>

              <div className="p-3 bg-zinc-950 rounded-lg border border-zinc-800">
                <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block mb-1.5">Files Involved</span>
                <div className="flex flex-wrap gap-2">
                  {signal.filesInvolved.map(file => (
                    <span key={file} className="px-2 py-1 bg-zinc-900 border border-zinc-800 rounded font-mono text-[11px] text-zinc-300">
                      {file}
                    </span>
                  ))}
                </div>
              </div>

              <div className="text-xs text-emerald-400 flex items-center gap-2 bg-emerald-500/5 p-2.5 rounded-lg border border-emerald-500/20">
                <span className="material-symbols-outlined text-sm">lightbulb</span>
                <span><strong>Recommendation:</strong> {signal.recommendation}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* TAB 3: God Files */}
      {activeTab === 'godfiles' && (
        <div className="space-y-4">
          {report.godFileCandidates.length === 0 ? (
            <div className="p-8 text-center bg-zinc-900/40 border border-zinc-800 rounded-xl text-zinc-400 text-xs">
              ✓ No critical God Files detected. Modularity is within healthy bounds.
            </div>
          ) : (
            report.godFileCandidates.map((god, idx) => (
              <div key={idx} className="p-5 bg-zinc-900/80 border border-zinc-800 rounded-xl space-y-3">
                <div className="flex justify-between items-start">
                  <div>
                    <h4 className="text-sm font-mono font-bold text-rose-400">{god.path}</h4>
                    <p className="text-xs text-zinc-400 mt-1">{god.reason}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="text-sm font-bold text-zinc-200 font-mono">{god.loc} LOC</span>
                    <span className="text-[11px] text-zinc-500 block">{god.incomingReferences} incoming refs</span>
                  </div>
                </div>

                <div className="p-3 bg-zinc-950 rounded-lg border border-zinc-800">
                  <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Distinct Mixed Responsibilities</span>
                  <div className="flex flex-wrap gap-1.5">
                    {god.distinctResponsibilities.map((resp, i) => (
                      <span key={i} className="px-2 py-0.5 bg-rose-500/10 text-rose-300 border border-rose-500/20 rounded text-[11px]">
                        {resp}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      )}

      {/* TAB 4: Git Churn */}
      {activeTab === 'churn' && (
        <div className="space-y-3">
          <div className="p-4 bg-zinc-900/60 border border-zinc-800 rounded-xl mb-4">
            <h4 className="text-xs font-bold text-zinc-300 uppercase tracking-wider">Top Hotspots by Git Churn (Past 30 Days)</h4>
          </div>
          {report.hotFilesByGitChurn.map(file => (
            <div key={file.path} className="p-3.5 bg-zinc-900/60 border border-zinc-800 rounded-xl flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400 font-mono text-xs font-bold">
                  {file.churnScore}
                </div>
                <div>
                  <span className="text-xs font-mono text-zinc-200 font-semibold">{file.path}</span>
                  <span className="text-[11px] text-zinc-500 block">{file.commitsInLast30Days} commits recently</span>
                </div>
              </div>
              <span className="text-[11px] font-medium text-purple-300 bg-purple-500/10 px-2.5 py-1 rounded-full border border-purple-500/20">
                High Churn
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
